project-stacker/stacker

README.md
Might not be where you want it, just an idea :)
=> add an example yamlfile to readme

stacker/unlade.go
Signed-off-by: Michael McCracken <mikmccra@cisco.com>
=> unlade: just some progress feedback

README.md
=> document btrfs step

vagrant/README.md, vagrant/Vagrantfile
=> add a vagrantfile

doc/stacker_yaml.md
I didn't know how it handles hashing directories so I didn't edit the next sentence. feel free to nack this and fix both sentences at once :)
=> add note about importing directories

import.go
When a parent directory is imported after it's children, it is removed and recreated.
When the "." directory gets imported it's destination path is incorrect.
Now the import logic only calls cp -a on files.
=> Fixed directory import

cache.go
Signed-off-by: Michael McCracken <mikmccra@cisco.com>
=> add a newline to pruning log

doc/install.md
skopeo is used by tests and available from projectatomic ppa.
=> install.md: document make check dep on skopeo and PPA for installation.

cmd/clean.go, storage.go
Otherwise it's a pain for the unpriv user to have to do it.
Closes #27
=> clean: remove btrfs subvolumes under roots

base.go, cmd/umoci.go
Umoci actually does try to lchown the newly initialized, empty,
oci layout when you unpack it.  So do so in a new userns.  This
requires a new 'stacker umoci init' subcommand since $golang.
Closes #30
=> fix unprivileged builds using tar and scratch imports

build.go
Signed-off-by: Ravi Chamarthy <ravchama@cisco.com>
=> add layer name to the generation message

doc/install.md
Fix https://github.com/anuvu/stacker/issues/36
=> Update documentation with new golang installation instructions

api.go, cmd/build-recursive.go, cmd/build.go, cmd/main.go, cmd/publish.go, cmd/validate.go, lib/image.go, publisher.go, test/publish.bats
`stacker publish` copies layers defined in stacker yaml files to a docker registry or oci layout
=> Add stacker publish

build.go, doc/tutorial.md
Provide an example using from:scratch.
=> from:scratch

base.go
The goal of the import here is to get whatever OCI stuff that already
exsits into the output image, so that we can add the new stuff on top of
this.
We were doing this incorrectly: we don't want to go to the first non-built
layer, in fact we want the closest reasonable layer to what's there now. So
instead of doing a recursive look through the layer definitions, let's look
at the base layer's output, if it doesn't exist, look for its input, and if
that doesn't exist, give up and put the whole rootfs in the next OCI
output.
Signed-off-by: Tycho Andersen <tycho@tycho.ws>
=> base: fix incorrect importing of base layers

cmd/unpriv-setup.go
Closes #73
Signed-off-by: Tycho Andersen <tycho@tycho.ws>
=> unpriv-setup: handle when our uid is in the target allocation

base.go, build.go, cmd/main.go, cmd/squashfs.go
(creating this PR now, but it's not yet ready)
=> upriv squashfs

doc/install.md
In addition to the F31 instructions there are some layout tweaks to
better support instructions for more than one Linux distro.
Signed-off-by: Paul Moore <pmoore2@cisco.com>
=> doc: update install.md with F31 instructions

cmd/umoci.go
Reverts anuvu/stacker#98
I indadvertently hit 'merge' on this. (I thought I was merging a different project :-()
=> Revert "Try to support unprivileged squash extract via squashtool."

.travis.yml, cmd/umoci.go, overlay/overlay.go, storage.go
A superset of #103; this makes it an error not to have squashtool when using squashfs imports with the btrfs backend.
=> Err on no squashtool btrfs

lib/image.go
1. Added creds field for source in ImageCopyOpts
- SrcUsername
- SrcPassword
=> lib/image: added creds field for source

btrfs/repack.go, overlay/metadata.go, test/squashfs.bats
See commit messages for details.
=> Build only base btrfs

btrfs/unpriv-setup.go, cmd/unpriv-setup.go
Ravi reported that unpriv-setup for overlay doesn't work because of permissions issues, let's fix that.
=> Unpriv setup fixes

test/import.bats, types/layer.go
A few minor nits with the new Import mechanism that I noticed while playing with it.
=> Import nits

go.mod, go.sum
=> mods: switch back to upstream go-losetup

test/dependency-order.bats, types/stackerfile.go
It is annoying to have stacker say "I can't figure out what your deps are"
without telling you what it couldn't resolve. Let's have it print these.
=> dependency calculation: print missing deps

go.mod, go.sum, lib/image.go
Raising this PR for comments, I am currently testing this change.
=> Add docker-daemon transport to the supported transports

lib/image.go, lib/image_test.go
=> lib: add copy option to set manifest type

.github/workflows/ci.yaml, Makefile, build.yaml
Useful if someone wants to build against some other liblxc to test or
whatever.
=> build: variablize lxc repo/branch

cmd/main.go
=> storage: switch the default to overlay

README.md
While I believe we only have internal contributions right now, someday we
may not.
=> README: note that external contributors have copyright

go.mod, go.sum
The mutator.AddExisting() API has landed upstream, so let's move back to
it.
=> deps: move back to upstream umoci

go.mod, go.sum
=> go deps: update to capture image-spec CVE fix

.github/workflows/ci.yaml
=> ci/cd: fix ci.yaml to publish built artifacts

Makefile, test/caching.bats
This has:
https://github.com/tych0/lxc/commit/2b113b55c72a1345035343603125901d85a38f43
which allows builds on alpine again.
=> build: use my fork of lxc

btrfs/utils.go, go.mod, go.sum, lib/hash.go
=> Revert "Switch uses of sha hasher to version which uses hardware accel when available"

README.md
=> README: adjust copyright year

go.mod, go.sum
=> deps: update for type confusion issue

overlay/pack.go
Note that the use of od.Digest in the AddExisting() call isn't quite
correct, but that's an existing bug filed in #247.
=> overlay: use umoci API for "add existing blob"

go.mod, go.sum
My patches were merged, hooray!
=> deps: move back to upstream go-losetup

test/dir-whiteout.bats
I wrote this trying to reproduce a bug, and couldn't. But hey, maybe it'll
catch a bug someday...
=> tests: add some tests for directory whiteouts

README.md, doc/hacking.md
=> doc: add some info about hacking/debugging stacker

doc/install.md
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
=> doc: updated dependencies for first time build

doc/tricks.md, test/overlay-dirs.bats
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
=> Bats test check file created in previous layer with overlayFS

doc/install.md
added apt install before all lines of package
Signed-off-by: Bogdan BIVOLARU <104334+bogdanbiv@users.noreply.github.com>
=> Added libsqushfs as dependency

doc/stacker_yaml.md
=> update annotations documentation

go.mod, go.sum
https://github.com/project-stacker/stacker/pull/346
```release-note
```
=> chore(deps): fix dependabot alerts

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> docs: fix issue templates

doc/stacker_yaml.md
=> docs: add info about "scratch"

README.md
=> docs: add pkg.go.dev badge

Makefile, build.yaml
=> ci: pass build version for static binary builds

.github/workflows/build.yaml, .github/workflows/release.yaml
=> ci: upload binary with the tag

pkg/stacker/import.go, test/import.bats
=> fix: import dest was always "/"

.github/workflows/stale.yaml
https://github.com/project-stacker/stacker/pull/379
```release-note
```
=> chore: fix dependabot alerts

pkg/types/layer.go, test/import.bats
Fixes issue #370
```release-note
```
=> fix: don't use quoting for paths during import

go.mod, go.sum
https://github.com/project-stacker/stacker/pull/398 https://github.com/project-stacker/stacker/pull/399
```release-note
```
=> chore(go.mod): fix dependabot alerts

build.yaml
=> chore: fix build

build.yaml, go.mod, go.sum
=> chore(deps): update deps for static stacker builds

.github/workflows/build.yaml, Makefile, pkg/log/log_test.go
=> test(cover): add ut for tracking coverage

README.md
=> docs(coverage): add status badge for codecov

pkg/lib/dir_test.go, pkg/lib/file_test.go, pkg/log/log_test.go
=> test: add more UTs

.github/workflows/build.yaml, .github/workflows/convert.yaml, .github/workflows/release.yaml, pkg/stacker/convert.go, test/convert.bats
We could have passed these into the "build_env:" directive, however it appears environment substitution is also allowed such as PATH=/usr/local/sbin:$PATH for that layer, which is harder to figure out. Instead just "export" them in the "run:" directive.
```release-note
```
=> feat(convert): export ENV vars

.github/workflows/convert.yaml
=> ci(convert): also enable triggering manually

.github/workflows/convert.yaml
"""
cache miss because layer definition was changed
error: layer needs to be rebuilt before publishing: alpine error: exit status 1
"""
```release-note
```
=> ci(convert): add missing substitute var

.github/workflows/convert.yaml
=> fix(ci): tag param is missing when publishing

test/caching.bats
Commit 9671d8f35986 disabled the caching.bats test "test can read previous version's cache".
This re-enables that test after updating it to use a specific value (v1.0.0-rc4) as the "previous version".
The change to use a specific version and use its released binary improves the test.  That improves the test for the following reasons:
* This should be faster - we don't have to build stacker twice.
* Ultimately testing against the last released version is probably what you want... that is the cache that your users have, not the last development commit.
* Building stacker from another version is both slow and hard to guarantee. This removes the assumption that the current build environment can build another version of stacker.
* There was assumed knowledge about both the current and other …
=> fix: update and re-enable test "test can read previous version's cache"

build.yaml
=> fix: build is broken again after alpine:edge updates

cmd/stacker/check.go
Add a check for remote-mounted filesystems like NFS.
https://github.com/project-stacker/stacker/issues/289
```release-note
```
=> fix: overlay and nfs don't work well together

test/caching.bats
=> test: update "previous" version to 1.0.0-rc5

README.md
So that nightly job failures (which are run async) are more explicit.
```release-note
```
=> docs: add a "nightly" badge

doc/install.md
documentation
none
Add missing dependencies in stacker documentation.
No
=> Document missing Ubuntu dependencies

pkg/squashfs/squashfs.go
In a single stacker file that used a squashfs image twice or more, stacker would mount the layers the first time correctly. The image build would fail.  The reason was that maybeKernelSquashMount did not detected *why* the mount failed (it was already mounted), but only that it did fail.  So the code then attempted to extract the squashfs layer with unsquashfs and an error would occur like:
FATAL ERROR: dir_scan: failed to change permissions for directory
.../roots/sha256_52068a5d6c1...02caeb3a706cba3a/overlay,
because Read-only file system
Parallel unsquashfs: Using 32 processors
691 inodes (966 blocks) to write
The error only actually occurs if:
* user is priveleged (can do a kernel mount)
* stacker is building squash images (--layer-type=squashfs)
* user does not have squashfuse in …
=> fix: recognize kernel mount failure when target already mounted.

test/squashfs.bats
=> test: add a squashfs and tar interop test

.github/workflows/sync-3rdparty-images.yaml
=> ci: fix image dest during copy

test/bom.bats
=> test: add a bom workflow with substitutions

ADOPTERS.md
=> docs: add a adopters file

test/convert.bats
python/3.11/alpine3.17 has been removed so update the test
```release-note
```
=> ci: fix "convert" test

pkg/stacker/bom.go
=> fix: incorrect snapshot used during bom stage

go.mod, go.sum
Pull in some improvements from stacker-bom such as include paths can be globs and verification speedups.
```release-note
```
=> chore: update stacker-bom dep version

go.mod, go.sum
Don't follow symlinks for checksum computation - they can be broken.
```release-note
```
=> chore: update stacker-bom version

test/bom.bats
=> ci: fix a failing test

go.mod, go.sum
This includes a change to add the uncompressed size of each layer of an image as an annotation.
=> fix: update umoci to 16c5101

pkg/container/container.go, pkg/log/log.go, pkg/squashfs/squashfs.go, pkg/types/layer_type.go, pkg/types/stackerfile.go
Fixed lint errors to ensure the nightly build passes.
=> chore: fix linter errors

.github/workflows/build.yaml, .github/workflows/coverage.yaml
codecov report upload is failing due to rate limiting
```release-note
```
=> ci: fix code coverage upload

.github/workflows/build.yaml, .github/workflows/ci.yaml, .github/workflows/coverage.yaml
Ensure that the coverage upload token is passed correctly.
```release-note
```
=> ci: fix coverage upload

.github/workflows/nightly.yaml
=> ci: fix nightly build workflow

go.mod, go.sum
=> fix: test whiteout fix

.github/workflows/release.yaml
=> fix: release workflow also needs the coverage token

.github/workflows/build.yaml, .github/workflows/coverage.yaml
=> ci: fix failing nightly builds

test/convert.bats, test/helpers.bash
=> ci: fix broken nightly (again)

README.md
=> docs: fix GH ci badge

.github/workflows/sync-3rdparty-images.yaml
=> ci: fix sync image sources

.github/workflows/release.yaml
https://github.com/actions/runner-images/issues/11101
ubuntu-20.04 runner is already retired.
```release-note
```
=> ci: update outdated runner
