project-stacker/stacker

- api.go
commit 4374239cca broke some builds by trying to skopeo copy
images to, say, "oci:oci:anuvu/anuvu-dev".  That's because
it dropped the 'path.Base(anuvu/anuvu-dev)'.  Re-add that.
> fix docker path

- container.go
If we bind mount a symlink to a directory, we want
the target directory bind mounted.
> use stat to determine bind mount type

- import.go
Signed-off-by: Paul Moore <paul@paul-moore.com>
> stacker: ensure that the dest dir exists in importFile()

- doc/install.md
The reference to golang 1.9 is incorrect now as things have moved on.
libcap-dev is needed for sys/capability.h
Signed-off-by: Scott Moser <smoser@brickies.net>
> doc: update to reference golang 1.10 and libcap-dev dependency.

- Makefile
- doc/install.md
'make check' uses bats package for unit tests and jq inside the unit
tests for verification.
> Mark dependencies for 'make check'.

- Makefile
It should be:
sudo ENV=VAL command
not
sudo command ENV=val
> Fix make check failure due to order of arguments to sudo.

- container.go
Currently stacker does not expose /dev/ptmx and does not mount /dev/pts this patch fixes this as it is needed by various software, ssh, python's test suite, etc
> Add support for pty's

- build.go
- test/scratch.bats
Alpine doesn't provide bash by default.  Which means we cannot
build FROM: alpine with a run: section.
> build.go: switch from bash to sh

- .gitignore
- api.go
- apply.go
- base.go
- build.go
- cache.go
- cache_test.go
- cmd/build.go
- deps.go
- go.mod
- go.sum
- lib/dag.go
- run.go
- test/prerequisites.bats
1. Changes in this PR
- Update the stacker recipe to add a 'stacker_config' key. The 'stacker_config' contains build configuration for all the layers in the stacker recipe. For now the only key in 'stacker_config' is 'include'. 'include' contains paths to other stacker recipes which contain layers which should be built before the current stacker recipe.
- Modified the 'stacker build' command to also build the layers mentioned in the 'include' section of the stacker recipe (and other includes found in those recipes, recursively). 
This behavior can be disabled with a '--no-includes' flag.
- Other changes which are prerequisites for the above.
2. If this PR is OK, we can move forward and:
- Add a separate command to search for stacker recipes in the file system using a regex, and arrange …
> Building multiple stacker recipes in same execution

- api.go
- base.go
- build.go
- cmd/build.go
- git.go
- test/save.bats
Feature can be useful if the remote is a docker registry, but can also work with an OCI layout as "remote".
Using an OCI layout is currently useful for testing purposes.
> Add the option to save the new layers to a remote location

- Makefile
- git.go
- test/basic.bats
Rather than spitting out a version that is simply a commit hash,
use output from git-describe.
Before:
$ stacker --version
stacker version 982c0032ce1a2cebf45d31904d920f20cabaa549
After
$ stacker --version
stacker version v0.4.0-78-gb16a7a1
> Use git describe to calculate a version.

- cache.go
- network.go
- test/import-http.bats
Fix for https://github.com/anuvu/stacker/issues/44
There are several cases:
- If the file is not in cache download it - covered by tests
- If the file is in cache but there's an error connecting to the server skip the download - covered by tests
- If the file is in cache and the shasum is present in HTTP head and matching the file cached locally skip the download - NOT covered by tests
- If the file is in cache and the content length in HTTP head matches the size of the file cached locally skip the download - covered by tests
- If the file is in cache and both the shasum and the content length are different from the file cached locally download the file - NOT covered by tests
> Stacker should do a HTTP HEAD call check the Content-Length and X-Checksum-Sha256 of the files imported using HTTP.

- api.go
- test/invalid.bats
In this case base images of type 'built' need to have a 'tag' which is not empty
> Add validation for stackerfile values

- cmd/main.go
I'm pretty sure this was just a bug that had stacker reading its
config file from the dubiously named ~/.config/conf.yaml.
Fixed here to now read ~/.config/stacker/conf.yaml.
> Read config from ~/.config/stacker/conf.yaml not ~/.config/conf.yaml.

- api.go
- cmd/chroot.go
I was wanting to do something like:
stacker chroot thing cat /etc/passwd > out
and the output would have warnings and "substituting" messages.
The solution here is just to very minimally get *those* messages
to stderr.
> Send some status/warning messages to stderr in the chroot path.

- Makefile
- import.go
- test/caching.bats
Closes #70
When a file under an imported directory is removed, calculate the
correct path to remove.
> import: remove the proper path

- container.go
Fix an error in my last patch which causes us to always print something
like
2020/02/14 22:38:37  warn failed parsing /etc/sub{u,g}idmap: <nil>
> Only print an error if there was an error

- api.go
- build.go
- publisher.go
This allows the stacker.yaml to reference stacker config.
It allows substitutions of:
STACKER_ROOTFS_DIR  RootFSDir
STACKER_STACKER_DIR StackerDir
STACKER_OCI_DIR     OCIDir
> Allow substitutions from stacker config into a stacker.yaml

- build.go
- doc/stacker_yaml.md
- test/config.bats
- test/helpers.bash
Follow on to #78 to:
- Remove debug Printf.
- Add test for config substitutions.
- Add some helpers for tests (umount_under, stderr, tmpd, cmp_files)
- Add some doc for config file substitutions.
> Add Config-value documentation and a test. Remove an inadvertant printf.

- build.go
- cmd/chroot.go
- container.go
- doc/stacker_yaml.md
- test/config.bats
- types/layer.go
- types/stackerfile.go
Now a run section will contain an environment variable
STACKER_LAYER_NAME.  The value is the name of the layer section
in the yaml file.
Fixes #95.
> Add STACKER_LAYER_NAME to the name of the layer to a build environment.

- cmd/umoci.go
This doesn't work right just yet, as squashtool has two bugs
a.) it does not extract symlinks
https://github.com/anuvu/squashfs/pull/1
b.) it does no perms at all without '--perms'
and if you pass --perms, then it will likely create
a dir that is un-writable and then try to extract into that.
But conceptually this is close.
> Try to support unprivileged squash extract via squashtool.

- base.go
- lib/image.go
- publisher.go
1. Add separate options for source and destination skip tls verification. 
2. Since SkipTLS verification was limited to source before, replaced SkipTLS option with SrcSkipTLS option wherever SkipTLS option is set.
> lib/image: added SkipTLS option for source and destination separately

- cmd/internal_go.go
- test/helpers.bash
31c298ee69a3 ("cmd: s/umoci/internal-go") changed the name of the internal
subcommand to umoci, but we didn't notice since we were allowing exit(1) as
an indication that we couldn't do overlayfs.
Instead, let's add an entrypoint to this hidden command that's just for the
testsuite, that tests the environment and exits with a special unused code
if it can't do overlay. This way if we eventually refactor this command
again and break it in the future, it will fail and we'll notice instead of
silently not running the unpriv tests for a while.
> tests: actually run unpriv tests again

- go.mod
- go.sum
This has the fix for ignoring trusted.overlay.opaque.
> deps: update umoci

- overlay/overlay.go
- overlay/pack.go
- test/multiple-output-types.bats
See the comments and the tests for cases where this can happen.
Essentially, chained type: built layers with no local changes can end up
generating layers with the same hash (but not always, whee). To fix this,
let's just allow -EEXIST errors from the "metadata syncup" syscalls, and
pretend they were successful.
Ideally, we'd be able to realize we generated this layer previously and
just re-use what we generated. However, this would require some additional
metadata somewhere in order to remember what unchanged built: type layers
we had generated. But that would require more spaghetti in some already
complicated code.
Closes #126
> overlay: allow layer collisions

- cmd/publish.go
- cmd/recursive-build.go
- test/prerequisites.bats
This regex will match anything containing stacker.yaml, including vim swap
files or things like test_stacker.yaml, which wouldn't be built by the
default "build" command.
Let's change this to match paths that end in /stacker.yaml, which is
probably as close semantically as we can get to the default build command.
> recursive-build, publish: narrow regex for stacker files

- cmd/internal_go.go
- overlay/pack.go
- test/unprivileged.bats
When using the overlay backend, individual layers are converted from
tar->squashfs when needed (in contrast with btrfs which converts the
underlying image wholesale, preventing sharing of bits). However, this
conversion happened in the host namespace, resulting in invalid images when
used in unprivileged mode.
Let's run this conversion inside a user namespace so we generate valid
images when converting them in this way.
> overlay: run layer conversion in a userns too

- base.go
- cache.go
- doc/stacker_yaml.md
- import.go
- network.go
- test/import.bats
- types/layer.go
- types/stackerfile.go
- supports both imports style:
```
import:
- path: path/to/file
hash: sha256sum
- stacker://first/example.txt
- http://url/to/file
```
> Support speciying hash of import source, closes #119

- .github/workflows/ci.yaml
- Makefile
- cmd/internal_go.go
- doc/install.md
- test/basic.bats
- test/caching.bats
- test/helpers.bash
- test/intermediate-base-snapshots.bats
- test/oci-import.bats
- test/squashfs.bats
This is the nth time the skopeo package install has broken our CI:
Unpacking containers-common (100:1-7) over (1.2.1~2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-at4ZRl/03-containers-common_100%3a1-7_all.deb (--unpack):
trying to overwrite '/usr/share/man/man5/containers-auth.json.5.gz', which is also in package containers-image 5.8.1~1
it looks like the OpenSUSE build infra for Ubuntu maybe just has a bug. But
it's probably pretty brittle anyway, since OpenSUSE doesn't care about
Ubuntu :). While the skopeo binary is available from the Ubuntu universe
repo starting in 20.10, github actions has no plans to support anything
besides Ubuntu LTS releases, so that doesn't help us for another 18 months.
Instead, let's switch to our own copy command. It's not that much code, and …
> ci/tests: move away from skopeo

- go.mod
- go.sum
The patches for ignoring overlay attributes have landed, so let's go back
to umoci upstream.
> go.mod: go back to umoci upstream

- cache.go
- cache_test.go
- test/caching.bats
If we run this new test with:
diff --git a/test/caching.bats b/test/caching.bats
index b2091d2..bbb0b20 100644
--- a/test/caching.bats
+++ b/test/caching.bats
@@ -185,7 +185,7 @@ EOF
@test "can read previous version's cache" {
git clone https://github.com/anuvu/stacker
-    (cd stacker && make)
+    (cd stacker && git co 481c315c8ca3c930fb8a215df8baf0b06bc38bc7 && make)
we get:
error: json: cannot unmarshal string into Go struct field Layer.cache.Layer.Import of type types.Import
This is because the commit after 481c315, 60cb730340ac ("Support
specifying hash of import source, closes #119") changed the cache
structure. We have a provision when the cache structure is changed: bump
the cache version so that things are completely invalidated and totally
rebuilt. However, this change snuck …
> cache: bump cache version + add a test

- lib/image.go
In spite of us setting our signature policy to
signature.NewPRInsecureAcceptAnything(), containers/image.copy() *still*
wants to read signatures (yes, even if there are none) from somewhere out
of /var/lib/containers. We need to set this new flag to prevent it from
trying to do so.
> lib/image: set RemoveSignatures

- test/docker-base.bats
The recent containers/image update generated a nasty stack trace in
unprivileged mode:
error: open /var/lib/containers/sigstore/library/centos@sha256=dbbacecc49b088458781c16f3775f2a2ec7521079034a7ba499c8b0bb7f86875/signature-1: permission denied
Error reading signatures
github.com/containers/image/v5/copy.(*copier).copyOneImage
/home/tycho/packages/go/pkg/mod/github.com/anuvu/image/v5@v5.0.0-20210310195111-044dd755e25e/copy/copy.go:652
github.com/containers/image/v5/copy.Image
/home/tycho/packages/go/pkg/mod/github.com/anuvu/image/v5@v5.0.0-20210310195111-044dd755e25e/copy/copy.go:330
github.com/anuvu/stacker/lib.ImageCopy
/home/tycho/packages/stacker/lib/image.go:115
github.com/anuvu/stacker.importContainersImage
which is fixed in the previous patch. We didn't catch this because we don't …
> tests: add a test for unprivileged docker hub importing

- .github/workflows/ci.yaml
- Makefile
- README.md
- btrfs/btrfs.go
- cmd/clean.go
- storage.go
- test/basic.bats
- test/build-only.bats
- test/caching.bats
- test/clean.bats
- test/config.bats
- test/container-setup.bats
- test/docker-base.bats
- test/env.bats
- test/helpers.bash
- test/import-http.bats
- test/intermediate-base-snapshots.bats
- test/main.py
- test/prerequisites.bats
- test/publish.bats
- test/squashfs.bats
- test/storage.bats
- test/unprivileged.bats
Rather than have some tests that we run unprivileged, and some that we run
privileged, let's run everything in both configurations so we can increase
coverage.
There are a bunch of changes to the testsuite needed; this is because the
testsuite runs as root, but we want to run stacker as non-root. So e.g.
when we do mkdirs or whatever for things stacker needs to be able to
read/write, we need to chown those in non-root mode.
This commit introduces the run_as helper, which runs things as the right
user in the test suite. Probably some more of the test suite modifications
could be ported to use this helper.
This commit also changes the way Clean() works slightly: the common clean
code no longer deletes (and thus no longer fails on deleting) the roots
directory. This is because in …
> tests: add an unprivileged axis to the test matrix

- .github/workflows/ci.yaml
This reverts commit 9f228230bc05090cea14df7e8182f79b4d43253c.
We don't need this cache clearing any more, so let's drop it.
> Revert "try to fix CI"

- cmd/main.go
If we run this in a userns, we won't have permissions to edit e.g.
/etc/subuid and /etc/subgid on the host.
This is a bit of a hack, but ctx.Args() in the app's Before() method has
argv[0] == $subcommand, so we 1. test that there is a subcommand and 2.
test that it is not unpriv-setup before we re-exec.
Closes #146
> unpriv-setup: don't run inside a userns

- build.go
- test/basic.bats
I have no idea why we did if/else here, but it seems fairly reasonable to
want both the stacker.yaml and the git hash (even if the git hash could
tell you the stacker yaml, it won't necessarily tell you the value of
--substitutions or whatever that people ran with). Let's include both.
> build: always annotate with the input stacker.yaml

- build.go
- test/caching.bats
Stacker will rebuild a cached layer if it uses bind mounts.  Emit an
info message so users understand stacker's behavior.
- Add a check in the cache test for the logged message
> Inform user that cached layers are rebuilt if bind mounts are used

- build.go
- test/caching.bats
We only want to emit the rebuildig message if the layer has been
built once and we have a cache hit.  Also switch back to bash pattern
matching in the test-case.  The previous attempt didn't account for the
fact that the output is a single line so matching a substring requires
accepting anything before and after the match.
> build: only emit rebuild message if cached and has binds

- btrfs/btrfs.go
- build.go
- cache.go
- cache_test.go
- doc/stacker_yaml.md
- lib/dir.go
- lib/file.go
- oci/oci.go
- overlay/metadata.go
- overlay/overlay-dirs.go
- overlay/overlay.go
- overlay/pack.go
- test/overlay-dirs.bats
- types/layer.go
- types/storage.go
```
overlay_dirs:
- source: example_dir
dest: /path/to/target
```
This will copy source's contents into dest
in the target image, preserving permission,
links, times but not ownership.
source's contents will be packed into a
layer and added to the final image.
> Add an overlay_dirs yaml entry

- import.go
This is a spiritual revert of the code in 9f46e4efbd23 ("import: handle
readonly parent directories") (but not the test); since we're now running
things inside a userns, the kernel's "is this thing root" checks pass and
we don't need to do this dance any more. Let's drop it.
> import: drop chmod removal

- container.go
Newer liblxcs reject starting on upstream kernels which don't have all the
same apparmor features that the Ubuntu kernels do. Let's set the flag so we
can actually run on upstream kernels. This avoids:
2021-06-04 10:51:18.478 |  lxc build-env 20210604165117.604 ERROR    apparmor - lsm/apparmor.c:apparmor_prepare:1111 - If you really want to start this container, set
2021-06-04 10:51:18.478 |  lxc build-env 20210604165117.604 ERROR    apparmor - lsm/apparmor.c:apparmor_prepare:1112 - lxc.apparmor.allow_incomplete = 1
2021-06-04 10:51:18.478 |  lxc build-env 20210604165117.604 ERROR    apparmor - lsm/apparmor.c:apparmor_prepare:1113 - in your container configuration file
2021-06-04 10:51:18.479 |  lxc build-env 20210604165117.605 ERROR    start - start.c:lxc_init:845 - Failed to initialize …
> lxc: allow "incomplete" apparmor profiles

- test/helpers.bash
- test/intermediate-base-snapshots.bats
As the comment says, if ubuntu changes the way they generate their images
and only distribute one layer, we'll have to do something different.
Well, they did change it and the :latest images are now one layer. Let's
make them two layers manually via `umoci insert` of a bogus file.
> tests: do a manual `umoci insert` to increase layer count

- build.go
- test/dependency-order.bats
- types/stackerfile.go
The problem here is that we explicitly allow and document stacker:// style
imports for the url: portion of tar: base layers, so people can compose
tarballs in one layer and emit them in other layers.
However, the dependency order calculation did not take into account this
dependency. Let's add it to the computation.
Additionally, we fix a comment on DependencyOrder(), since it *does* in
fact re-order things now (and the comment had some poor grammar...)
> tar base layers: fix computation of dependency order

- Makefile
- build.yaml
This will be useful for network-internal builds of stacker who can't
reference docker://alpine:edge directly.
> build: variablize base image URL

- Makefile
Some things in the go cache are imported as -w, and so rm does interactive
prompts for these, which is annoying.
> make: add -f to clean

- build.yaml
This has the patch for the "statically linked init", which will hopefully
give us a completely statically linked stacker.
> build: use my LXC fork

- import.go
- test/import.bats
There are two bugs here we fix.
1. lib.DirCopy() is recursive, but we the list of diffs is also recursive.
So for a diff list like:
/a
/a/b
/a/b/c
we would end up copying c *three* times, once for /a, once for /a/b, and
once for /a/b/c. While we switched away from cp -a to lib.DirCopy()
recently, the bug existed previously with the cp -a version too. We've
done lots of i/o we didn't need to do. c'est la vie :)
2. A correctness bug: go-mtree generates the diff list by putting paths in
a golang map. golang maps are randomized, and thus the diff list can be
generated in any order. So, for example, the diff list above could also
be:
/a/b/c
/a/b
/a
Previously, on any new file, we would always os.RemoveAll() the target
(in case the file switched from being a file to a directory, for
example). …
> import: fix poor behavior

- Makefile
- build.yaml
- cmd/main.go
Now that we're statically linking liblxc, it will likely be useful to know
exactly what version we're using:
~/packages/stacker master ./stacker --version
stacker version stacker v0.9.3-1-g2a431db-dirty liblxc e75ce64052f6c24790f5b2a98c617f29734a5165
~/packages/stacker master ./stacker-dynamic --version
stacker version stacker v0.9.3-1-g2a431db-dirty liblxc 4.0.9
Unfortunately the dynamically linked stacker doesn't exactly represent the
right version because liblxc's pkgconfig doesn't report it correctly (this is
some development version off of 4.0.9), but for the one that matters, the
statically linked one, we use rev-parse and thus should always get a hash.
> cmd: add lxc version to --version output

- go.mod
- go.sum
- overlay/metadata.go
- overlay/pack.go
- test/build-only.bats
The problem here was in our "do changes exist" detection in
generateLayer(). We just tested if the overlay/ working directory was
empty.
However, on previous builds where there were intermediary build_only
layers but a final OCI output, we would go through and generate an OCI
layer for each of the intermediary build layers.
Then the rebuild would go through, and if none of the contents of these
layers changed in a build, they would be ignored since there were no
changes.
Let's add a flag to indicate "hey, we actually built this earlier, you
should grab the output from there" if there are no changes. Note that an
empty dir really does mean no changes, since if someone deletes stuff (or
changes file metadata, or whatever), overlay will generate a whiteout node
or do a copy_up() to have …
> overlay: fix re-build of build-only overlay layers

- cmd/internal_go.go
The kernel's procfs code disallows writing to /proc/pid/attr/current from a
different task:
static ssize_t proc_pid_attr_write(struct file * file, const char __user * buf,
size_t count, loff_t *ppos)
{
struct inode * inode = file_inode(file);
struct task_struct *task;
void *page;
int rv;
...
/* A task may only write its own attributes. */
if (current != task) {
rcu_read_unlock();
return -EACCES;
}
...
golang spawns lots of threads to do work in. /proc/self always refers to the
leader of the thread group, which may not be the task actually doing the
ioutil.WriteFile() (and indeed, most of the time is not), so we'd mostly (but
not always) get EACCES here.
Further, there is another race, since this check is done on write() and not
open(), if we open() things in one thread, and then write() …
> internal: fixup apparmor profile detection

- .github/workflows/ci.yaml
mostly it'll be interesting to see if the new register allocator will be
substantially faster for all of our pure go tar/gzip usage, which is mostly
what dominates stacker's cpu time.
> ci: run with go 1.17 too

- overlay/metadata_test.go
If the overlay metadata structure changes, it probably implies a bug fix or
some other change in behavior, which previous overlay metadata will not
satisfy (even though they'll unparse correctly, the fields will just have
their "zero" value).
See the comment in TestCacheEntryChanged() for a full explanation, but
basically we should re-build everything if this structure has changed,
which means we should have a test for when it changes so that if people
change it, they know to bump the cache version.
> overlay: test that the overlayMetadata structure is unchanged

- import.go
- network.go
- test/import.bats
This builds on top of 60cb730
Before this commit it only checked  HTTP header "X-Checksum-Sha256" with the hash provided in stacker.yaml
Now it also verifies the sha256 of the newly downloaded file on top of existing checks
Also resolves ~part1 of #206
> import: add a hash check for http(s) imports 

- build.go
- cache_test.go
- cmd/build.go
- cmd/chroot.go
- doc/stacker_yaml.md
- publisher.go
- test/import.bats
- types/stackerfile.go
- types/stackerfiles.go
- types/types_test.go
when stacker build is called with the flag `--require-hash`, it will fail the build if any remote import (http/https) doesn't have hash in its yaml entry.
```
--require-hash                  require all remote imports to have a hash provided in stackerfiles
```
*It still allows local or stacker imports without the hash*
Closes anuvu/stacker#206
> import: add flag to verify hash in remote imports

- go.mod
- go.sum
- lib/image.go
With these flags containers/image now seems to correctly not try to
recompress squashfs images.
I tried to pinpoint where exactly this happened in the containers/image
tree, but it wasn't obvious :)
Note that we pass these two OCI "please don't compress things" flags, as
without those it doesn't seem to work. Maybe I just overlooked those
before? Not clear.
> deps: move back to upstream containers/image

- container/container.go
- container/idmap/idmap.go
- container/userns.go
Users of the "container" package now have to link against liblxc, and this
idmap code is useful on its own.
> container: move idmap stuff to its own package

- Makefile
`stacker clean` will work fine here for the stacker generated dirs, so long
as stacker was actually built successfully (which in some cases it may not
be). However, we put the go build cache in .build as well so we don't have
to re-download everything, and it creates files that are only +r for the
current user. rm -rf can't delete these for whatever reason, only root in a
user namespace can do that without first making it +w.
So, let's just be root in a user namespace. That fixes the problem with
broken stacker builds failing to clean things as well.
> makefile: use better clean mechanism

- btrfs/utils.go
- go.mod
- go.sum
- lib/hash.go
Go standard library crypto/sha256 does not use sha2 hardware instructions or AVX-512 when available.  This patch increases byte/cycle hash rate by 4x-8x by using a drop in replacement library.
This adds a new library that is Apache 2.0 licensed, and updates a dependency library that is MIT licensed.
This came out of looking for low hanging hash rate speed ups after running into problems with this issue:  https://github.com/anuvu/stacker/issues/210
> Switch uses of sha hasher to version which uses hardware accel when available

- .github/workflows/ci.yaml
- cmd/main.go
- container/container.go
- doc/install.md
Make check with a newer golangci-lint flagged some valid issues.
Channels for signal propagation need to be buffered.  Otherwise a dead lock can occur as unbuffered channels block the sender until the receiver checks for the message.  Real bad behavior if for instance the signal is on the same kernel thread as the go routine that's waiting for the signal.
An err variable was ignored.  The change simply prints the error and continues to maintain the existing semantics but adding debugging bread crumbs.  I welcome alternative suggestions for expected behavior.
Updated the docs with what was needed for the development lifecycle on a fairly fresh Ubuntu 20.04.  The ppa hasn't been updated for focal, but doesn't appear to need to be required.  Several packages commonly already installed …
> Fix make check

- btrfs/utils.go
- go.mod
- go.sum
- lib/hash.go
Reverts anuvu/stacker#229
Reverts the revert.  The scare that caused the revert doesn't affect the code.
The concern was that minio/sh256-simd can be convinced to construct an Avx512 hasher.  That Avx512 hasher both occasionally gives incorrect results(!), in addition to causing a performance regression vs avx2 on some platforms.  It seems minio knows this as there's no way to select the Axv512 hasher via the drop in replacement functions for golang crypto/sha256 we're using.
> Revert "Revert "Switch uses of sha hasher to version which uses hardware accel when available""

- doc/running.md
as of 9c22a7fe2cb0 ("storage: switch the default to overlay"), stacker
defaults to overlay storage. update the docs to reflect this.
> doc: update docs to reflect overlay default-ness

- Makefile
Now that the stable-4.0 branch has my cgroups compiler fix, we can go back
to upstream.
> build: go back to lxc stable-4.0

- test/squashfs.bats
Seems as though there's some network suckage here:
+ yum install -y wget
CentOS Linux 8 - AppStream                       63  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Let's just mutate the layers in a different way.
> tests: don't yum install

- go.mod
- go.sum
This is effectively a revert of 81bb45693a67 ("deps: move back to upstream
containers/image"), but with a newer containers/image.
It turns out our tests do not test uploading (i.e. transitioning) squashfs
images across OCI -> docker, which breaks with this change.
> deps: revert to our containers/image fork

- lib/image_test.go
> tests: use umoci API for adding a non-compressed blob

- squashfs/squashfs.go
> squashfs: fix squashtool url

- .github/workflows/ci.yaml
This matrix column was deleted in 5f896b9f3771 ("*: delete the btrfs
storage backend"), but this is leftover. Let's drop it too.
> ci: drop dead references to storage-type

- .github/workflows/ci.yaml
- atomfs/molecule.go
- atomfs/oci.go
- cmd/internal_go.go
- squashfs/verity.go
- test/atomfs.bats
Let's get rid of the FIXME's and make re-use of existing devices actually
safe. We can access the existing root-hash through device-mapper directly
(there does not seem to be any way through cryptsetup). Of course, there is
no static-build-able version of libdevmapper bindings anywhere (the only
real bindings are in moby/docker, and they disabled static builds some time
ago). So, let's just write our own tiny bit of cgo for the stuff we want to
extract.
Note that there is already a test case for the happy path: the third test
case in test/atomfs.bats relies on pre-existing verity devices, so we only
add a negative test case here.
> atomfs: verify root hash for existing devices

- atomfs/molecule_test.go
again, the bats-based tests are the positive case here, so let's just make
sure it fails when there's no verity data present.
> atomfs: add test for AllowMissingVerityData

- Makefile
- squashfs/verity_static.go
this way downstream golang projects don't have to know to pass all this
extra nonsense in their builds, they get it for "free".
we do it in this strange way with static_build because newer versions of
cryptsetup (in particular, the latest version, which we're building to
statically link against) depend on json-c, which is not in a lot of repos
(e.g. ubuntu 20.04).
so in order to work around this, we only expose these flags when we
actually need them, when doing a static build.
> squashfs: rearrange the way we pass ldlibs

- .github/workflows/ci.yaml
note that there *is* motivation for keeping golang 1.17 around:
golangci-lint only runs certain linters with golang 1.18 right now,
because generics broke the AST apparently.
So, let's keep 1.17 around and make sure that those linters still run,
since eventually they'll be re-enabled and this way we won't have to go
through and fix everything when they are.
> ci: add go 1.18 to CI

- cmd/main.go
- test/basic.bats
We were getting something like:
panic: runtime error: slice bounds out of range [:2] with capacity 1
goroutine 1 [running]:
main.main.func3(0xc0005ca000)
/stacker-tree/cmd/main.go:289 +0xb55
github.com/urfave/cli.(*App).Run(0xc0005b4000, {0xc000110200, 0x1, 0x1})
/stacker-tree/.build/gopath/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:264 +0x56d
main.main()
/stacker-tree/cmd/main.go:297 +0x120b
derp :)
> cmd: stacker with no args shouldn't crash

- storage.go
We're always using the overlay backend now, since we only have one storage
backend, so let's drop this.
> storage: drop "using storage backend overlay" message

- .github/workflows/build.yaml
- cmd/publish.go
- lib/image.go
- publisher.go
- test/publish.bats
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>
> publish: added skip-tls flag for uploading to a insecure http registry

- build.go
- build.yaml
- cmd/build.go
- cmd/chroot.go
- cmd/validate.go
The problem here is as follows:
1. user deletes the /bin -> /usr/bin symlink (e.g. via tar command without
--keep-directory-symlink or an rsync without --keep-dirlinks)
2. layer is created
3. build on top of that layer fails because /bin doesn't have sh in it any
more.
Both centos7 and ubuntu have this /bin -> /usr/bin construction, so let's
default to that.
Of course, because everything is wonderful, alpine only ships /bin/sh, and
does not have a /usr/bin -> /bin symlink, so stacker's own build breaks
without explicit shebangs. But best to use what downstream users expect.
> build: switch the default shell to /usr/bin/sh

- git.go
> git: drop unused function

- test/basic.bats
- test/helpers.bash
The fix for
https://github.blog/2022-04-12-git-security-vulnerability-announced/ breaks
stacker's test suite, since the directories are owned by a user, but for
the privileged tests git is invoked as root. Let's write a wrapper to
always invoke it as the right user.
> tests: fix git cve fix breakage

- doc/install.md
After some trial and error trying to configure make check to work on my Ubuntu 22.04 LTS vm, I wrote down the extra steps I needed to take. This will hopefully help with the onboarding process of new devs. These extra steps were tried and confirmed working on @Andreea-Lupu 's xUbuntu 22.04 vm.
Signed-off-by: Catalin Hofnar <catalin.hofnar@gmail.com>
> Updated install.md for Ubuntu 22.04

- build.go
When stacker builds a container, it uses the s.TemporaryWritableSnapshot(name)
results.  This can be > 63 chars, which lxc will balk at.  For instance:
error: failed setting config lxc.uts.name to temp-snapshot-build-cluster-api-provider-sveltos-amd64-2544038502: setting config item for the container failed
We don't actually need a good name for the container, it just needs to run.
So just use "stacker".
If we care, we could instead do something only if len(name) > 63...
Signed-off-by: Serge Hallyn <serge@hallyn.com>
> Avoid too long utsnames

- test/overlay-dirs.bats
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>
> Unpack overlay-dirs containers in tests

- api.go
- build.go
- cmd/build.go
- squashfs/verity.go
- test/annotations-namespace.bats
- test/basic.bats
added --annotations-namespace arg
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>
> Added a flag to specify OCI annotation namespace

- cache.go
- test/helpers.bash
- test/overlay-dirs.bats
This PR implements the suggestions from issue #159.
Without --debug, it will print the first 2 changed dirs:
```
cache miss because content of 3 overlay dirs changed:
/home/chofnar/stacker/f2
/home/chofnar/stacker/f3
and 1 others. use --debug for complete output
```
With --debug, it will print all modifications:
```
cache miss because content of 3 overlay dirs changed:
/home/chofnar/stacker/f2
/home/chofnar/stacker/f3
/home/chofnar/stacker/f4
```
Newest change also lists the files that changed:
With --debug
```
cache miss because content of 4 overlay dirs changed:
Changed overlay_dir: /home/piggie/stackeryamls/od1
Contents that changed:
/home/piggie/stackeryamls/od1/subdir/subdirfile.txt
/home/piggie/stackeryamls/od1/file1.txt
Changed overlay_dir: /home/piggie/stackeryamls/od2
Contents …
```
> Added logging for changed overlayfs dirs

- test/overlay-dirs.bats
Test is assumming the map where modified overlay-dirs is sorted.
Signed-off-by: Petu Eusebiu <peusebiu@cisco.com>
> Fix bug in overlay-dirs cache test

- build.go
revert this part of f4484f8
"/bin/sh" is more likely to be found than "/usr/bin/sh" - Debian for example!
> revert default shell to "/bin/sh"

- build.go
- cache_test.go
- doc/stacker_yaml.md
- test/multi-arch.bats
- types/layer.go
> feat: support writing os/arch info image config

- overlay/overlay.go
This will cause all upperdirs to user user.overlay.* instead of trusted.overlay.* xattrs.  Since a root user may generate a layer which will later be used as a base by an unprivileged build, there's no reason to ever use trusted.*.
Signed-off-by: Serge Hallyn <serge@hallyn.com>
> Mount overlay with userxattr option

- go.mod
- go.sum
- overlay/pack.go
The overlay attributes [1] have given us some grief [2]. They don't seem to provide benefit.  We are keeping the overlay.opaque values, but drop everything else in *.overlay.* namespace.
[1] https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html 
[2] https://github.com/vasi/squashfuse/issues/78
> Drop overlay attributes before creating squashfs.

- cmd/check.go
stacker check command now verifies if the newuidmap binary exists in PATH and if the binary is executable with setuid bit on.
Fixes #324
Signed-off-by: Ravi Chamarthy <ravi@chamarthy.dev>
> check: update stacker check to verify newuidmap

- doc/stacker_yaml.md
the section header depths made the outline weird, they should match the levels in the actual yaml, except for `import hash` which seemed enough like a sub-type that I left it as a child of `import`.
Signed-off-by: Michael McCracken <mikmccra@cisco.com>
> stacker_yaml doc: fix indenting

- lib/dir.go
- overlay/pack.go
You cannot have user.* xattrs on a symlink.
Except...  overlay is in the kernel, it can do what it wants. Unfortunately, fs/xattr.c:xattr_permission() won't allow us to do anything with them:
124         /*
125          * In the user.* namespace, only regular files and directories can have
126          * extended attributes. For sticky directories, only the owner and
127          * privileged users can write attributes.
128          */
129         if (!strncmp(name, XATTR_USER_PREFIX, XATTR_USER_PREFIX_LEN)) {
130                 if (!S_ISREG(inode->i_mode) && !S_ISDIR(inode->i_mode))
131                         return (mask & MAY_WRITE) ? -EPERM : -ENODATA;
So just skip trying to remove any xattrs on symlinks.
This *should* be ok, because if I do mksquashfs of a directory with a symlink …
> Explicitly avoid trying to remove xattrs on symlink

- build.go
- cmd/build.go
- log/log.go
- test/basic.bats
Currently, all substitution args must be specified on command-line. Sometimes convenient to add them all in a file and read that file.
```release-note
```
> feat(build): add a substitute-file option

- Makefile
- test/helpers.bash
Dependance on docker:// urls are painful because of docker quotas. At my large corporation, the docker.io quota is spent most of the time by afternoon.
Currently, stacker build/check depends on docker.io (docker://) urls in these places:
* build uses docker://alpine:edge - this can already be set via STACKER_BUILD_BASE_IMAGE to some other alpine url.
* docker://centos:latest - now can be set in STACKER_DOCKER_BASE_CENTOS
* docker://ubuntu:latest - now can be set in STACKER_DOCKER_BASE_UBUNTU
The change here allows these urls to be configured as a group by setting STACKER_DOCKER_BASE such as one of these:
make STACKER_DOCKER_BASE=docker://your-local-zot/stacker-deps/
make STACKER_DOCKER_BASE=oci:/data/sdeps:
or individually like:
make STACKER_BUILD_BASE_IMAGE=docker://alpine:edge \ …
> Reduce build and test dependency on docker:// urls.

- squashfs/squashfs.go
feat: Use squashfuse_ll if available for faster squashfs.
squashfuse README says of squashfuse_ll:
>   Like `squashfuse`, but implemented using the low-level
>   FUSE API. It's a tiny bit faster, but less portable.
But some reports say things like "30x times faster."
https://github.com/snapcore/snapd/pull/7477
> use squashfuse_ll if it is available.

- base.go
- build.go
- cache.go
- cmd/grab.go
- cmd/internal_go.go
- cmd/main.go
- doc/stacker_yaml.md
- grab.go
- import.go
- lib/dir.go
- lib/file.go
- network.go
- overlay/overlay-dirs.go
- test/import.bats
- types/layer.go
Currently, "import:" directive only allows for temporarily mounting previously layers, and actual copying would have to be done via "run:" directive. But in cases where there is no shell in the current layer, there was no way to achieve this, greatly limiting usability for packaging golang binaries.
Adding support using "dest:" option under "import:" directive.
```release-note
```
By …
> feat(import): add "copy" support for import

- test/binds.bats
- types/layer.go
As per the type definition of Layer, bind is of type Bind which is a
struct with fields Source and Dest.
But when we do UnmarshalYAML for type Bind, we are assuming that we
would always get the Bind as a []string and not
[]map[interface{}]interface{} (when making a call to
getStringOrStringSlice).
This PR fixes the getStringOrStringSlice to consider Bind defined
as a []map[string]string and returns appropriate bind string
in that case.
Fixes https://github.com/project-stacker/stacker/issues/301
> fix(bind): interpret bind defined as type []map[string]string 

- squashfs/squashfs.go
If stacker build is being run as "real root", then use a kernel mount rather than using squashfuse.
**What does this PR do / Why do we need it**: Maybe we dont.  It seems unreasonable to hamstring root into only doing fuse mounts when he/she could have the kernel do them.
I expect some discussion would be needed here.  I'm thinking that maybe environment variable configuration to turn this on or off would be useful.  Maybe default to fuse and allow the root user of stacker to use kernel mounts by setting STACKER_SQUASHFS_KERNEL_MOUNTS=true . or something.
> Use kernel mount of squashfs if running privledged.

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Makefile
Disable annotated tagged releases and just rely on GitHub release pipeline.
Disable periodic builds.
Add the release tag in the binary's version.
```release-note
```
> ci: fix release pipeline

- .github/workflows/build.yaml
- Makefile
- README.md
Pass the tag and short-sha to VERSION_FULL in the Makefile during release build.
```release-note
```
> ci: update release workflow to properly include the version

- pkg/atomfs/molecule.go
- pkg/squashfs/squashfs.go
- pkg/squashfs/verity.go
- pkg/squashfs/verity_test.go
Support mounting atomfs stacks as root in a container.
> feature: Support atomfs molecule mount in containers

- .github/workflows/ci.yaml
- .github/workflows/cloc.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yaml
- go.mod
> chore: update to golang 1.20.x

- cmd/stacker/publish.go
- pkg/stacker/publisher.go
- test/publish.bats
Currently, publish cmd will push every layer in a stacker.yaml file by default.
This patch adds support to push only required layers.
```release-note
```
> feat(publish): add ability to select specific layers to publish

- .github/workflows/build.yaml
Currently the "Build and test" step of the c-i workflow does both build a binary and test the binary.  Make 2 sections 'Build' and 'Test'. This way you can know which of the two sections failed, and also see how long each portion took.
```release-note
```
> Separate build and test in github workflows.

- .github/workflows/build.yaml
- pkg/squashfs/squashfs.go
- pkg/squashfs/verity.go
This protection was present in one of the callers of squashFuse, but not in another.  The change here just to put them inside squashFuse.
Fixes #428.
```release-note
```
> Fix race condition in stacker's squashfuse mount path.

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
- .github/workflows/convert.yaml
- .github/workflows/release.yaml
Currently, the github workflows dependencies are chained as follows:
build.yaml -> ci.yaml
release.yaml -> ci.yaml
convert.yaml -> ci.yaml
build.yaml and release.yaml are inline builds but operate on different build triggers. convert.yaml is timer-based and works offline.
```release-note
```
> fix(ci): add a "build-id" input var to ci builds

- cmd/stacker/main.go
- pkg/types/config.go
- test/args.bats
Fixes issue #377
```release-note
```
> feat: add a single working-dir option

- cmd/stacker/check.go
- pkg/stacker/check.go
stacker functionality depends on kernel versions and filesystem support. So useful to report this often, at least to debug issues.
```release-note
```
> feat: report kernel version and fs type

- .github/workflows/build.yaml
- Makefile
- build.yaml
workflow:
* add Setup Environment section that defines GOPATH and set GOPATH to <checkoutdir>/.build/gopath and GOCACHE to <checkoutdir>/.build/gocache/gocache.
This means that all 'go' operations in subsequent sections will have that variable set.  The go toolchain will then correctly re-use anything it can throughout the build.
Note these are the same values that use of Make will set both inside and outside the stacker build.
(stacker build dir is bind'd into the build environment and Make will set the variable correctly inside also, so the static build will benefit from a cache that the dynamic build did)
* Separate out 'go mod download' from the build.  This makes better information available on how long operations things took.
Because GOMODPATH is shared, these will used both by the …
> Build improvements

- .github/workflows/convert.yaml
- cmd/stacker/build.go
- cmd/stacker/check.go
- cmd/stacker/chroot.go
- cmd/stacker/clean.go
- cmd/stacker/convert.go
- cmd/stacker/gc.go
- cmd/stacker/grab.go
- cmd/stacker/inspect.go
- cmd/stacker/internal_go.go
- cmd/stacker/main.go
- cmd/stacker/publish.go
- cmd/stacker/recursive-build.go
- cmd/stacker/unpriv-setup.go
- cmd/stacker/validate.go
- go.mod
- go.sum
- pkg/stacker/build.go
- pkg/stacker/convert.go
- pkg/stacker/publisher.go
> fix(ci): convert ci is failing due to perms

- build.yaml
Top commit (54b6501b188041019c19dd6d93c66838bae6c165) on alpine zstd tree commit says:
main/zstd: split -static
That broke our build as the new zstd-dev does not contain a libzstd.a.
Thankfully the fix is as easy as adding zstd-static to the list of alpine packages in the container.
> Fix link failure by adding zstd-static to the alpine build container.

- .github/workflows/build.yaml
- build.yaml
- doc/install.md
- go.mod
- go.sum
- pkg/squashfs/superblock.go
- pkg/squashfs/verity.go
- pkg/squashfs/verity_test.go
- test/caching.bats
stacker was only using anuvu/squashfs import to get the size of the squashfs file (from its superblock, rather than from 'stat').
That go library used libsquashfs-tools-ng as a c-go dependency, which meant a build and runtime dependency on it.
The change here is to drop that import and instead use some native go.
> Feature/no more anuvu/squashfs dep

- test/main.py
The bats test framework provides '--timing' flag that will ammend its "tap" output with test duration information.
Per-test test output is then changed like this:
```
- ok 1 invoking foo with a nonexistent file prints an error
+ ok 1 invoking foo with a nonexistent file prints an error in 1sec
```
Not terribly useful, but better than nothing.
Also here change '-t' to the more readable long form '--tap'.
> feat: Add some duration information to test output.

- pkg/stacker/import.go
- pkg/stacker/network.go
- test/import-http.bats
Fixes issue #456
```release-note
```
> fix: support dest path for import-http

- build.yaml
bug
fixes #473
Enables alpine:edge aarch64 image to finish building (allows it to compile C programs).
Signed-off-by: Ashwin Gopalan ashwin.gopalan02@gmail.com
> fix: added build-base to package list for static build

- doc/stacker_yaml.md
--require-flag was a typo
take the opportunity to add some extra detail and be clear about what happens with that flag.
This is a documentation PR
No issue was filed.
fixes an error in the docs
see https://stackerbuild.io/v0.40.1/reference/stacker_file/?h=hash#import-hash
no testing, yolo
see above re: yolo
Let's hope not
Not during usage.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> doc: fix typo in --require-hash and add detail

- pkg/stacker/convert.go
- test/convert.bats
Bug
```bash
ENV foo /bar
ENV foo=/bar
ENV TEST_PATH="/usr/share/test/bin:$PATH" \
TEST_PATHS_CONFIG="/etc/test/test.ini" \
TEST_PATHS_DATA="/var/lib/test" \
TEST_PATHS_HOME="/usr/share/test" \
TEST_PATHS_LOGS="/var/log/test" \
TEST_PATHS_PLUGINS="/var/lib/test/plugins" \
TEST_PATHS_PROVISIONING="/etc/test/provisioning"
```
The PR adds support for the 3rd kind
For the `stacker convert` to handle Dockerfile with ENV defined in the form:
```
ENV TEST_PATH="/usr/share/test/bin:$PATH" \
TEST_PATHS_CONFIG="/etc/test/test.ini" \
TEST_PATHS_DATA="/var/lib/test" \
TEST_PATHS_HOME="/usr/share/test" \
TEST_PATHS_LOGS="/var/log/test" \
TEST_PATHS_PLUGINS="/var/lib/test/plugins" \ …
```
> fix(convert): handle conversion of multiple ENV in oneline  in Dockerfile

- test/caching.bats
This test is currently broken as a current version of stacker cannot read an old version's cache.  The change was intended, to clean up /stacker under c68147cba8d.
```release-note
```
> Disable test 'can read previous version's cache'

- build.yaml
Its been a long time that this has been broken.  The run sections in build.yaml were executing shell scripts without '-e' and thus they would not exit on failure.
The end result was that if something went amuck you had to parse through long error logs for what that was.
Also add '-x' here to make it more obvious where things failed.
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of …
> fix: build.yaml run section needs set -e, and add -x

- cmd/stacker/chroot.go
- cmd/stacker/lxc-wrapper/lxc-wrapper.c
- pkg/container/container.go
- pkg/stacker/bom.go
- pkg/stacker/build.go
- pkg/stacker/grab.go
- test/bom.bats
* refactor: Bind stacker binary into container in SetupBuildContainerConfig
Previously there were 3 individual calls to bind stacker into
tools/static-stacker.  This just changes that to 1 place, so
after calling SetupBuildContainerConfig you can use stacker inside.
* test: Change bom test to contain spaces
The bom test case previously had Author of 'bom-test',
which was not realiastic and was intentional to avoid
exposing the bug with spaces.
* fix: Use arrays for execution rather than scalar string.
This changes the interface for container.Execute to be an
array of strings rather than a string, and then changes
the internal lxc-wrapper pass arguments provided to it
through to the lxc 'start' api call.
It ultimately allows us to safely call programs with spaces,
quotes or other "odd" …
> feat: Support spaces in bom author/vendor and cmd exec inside lxc.

- pkg/overlay/metadata.go
A comment in metadata.go says that
> overlayfs doesn't work with < 2 lowerdirs, so we add some
That doesn't seem right, you definitely do need 1 lowerdir, but you do not need 2.
> fix: only use workaround for overlay if there are zero lowerdirs

- pkg/atomfs/molecule.go
Without xino=on you can end up with duplicate inodes numbers in theo same overlayfs  filesystem.
```release-note
```
> Mount atomfs molecule with overlay filesystem with xino=on.

- pkg/atomfs/molecule.go
- pkg/overlay/metadata.go
fix: clarify comments in molecule.Mount and lxcRootfsString
molecule.overlayArgs provides options for a kernel mount-option string.
Kernel mount options for overlay require *more* than one lowerdir if
there is no upperdir.  molecule.Mount always performs read-only
mounts (thus no upperdir). So molecule.overlayArgs must add
a workaround lowerdir if there is only one.
Separately, lxcRootfsString function returns a string to be supplied to
lxc's lxc.rootfs.path.  lxc.rootfs.path is of the form:
overlayfs:lowerdir[:lowerdir2:lowerdir3]:upperdir.
It requires 1 or more lowerdirs and an upperdir.
So in lxcRootfsString we need to create a workaround dir only if there
are zero lowerdirs (an empty container).
Signed-off-by: Scott Moser <smoser@brickies.net>
this is a follow-on to …
> fix: clarify comments in molecule.Mount and lxcRootfsString

- .github/workflows/build.yaml
- Makefile
- pkg/stacker/publisher.go
- test/bom.bats
- test/helpers.bash
> test: add a bom test for derived images

- test/bom.bats
- test/convert.bats
- test/helpers.bash
These tests are extremely slow.  We should probably use a different container to test them in.  A recent run of c-i showed:
ok 19 all container contents must be accounted for in 2617sec
ok 20 bom tool should work inside run in 1233sec
So these 2 tests accounted for 3850 seconds (64 minutes).
```release-note
```
> test: Mark the bom tests as slow.

- pkg/overlay/overlay.go
When we run a stackerfile a second time, previously built tar layers are assumed to already exist.  But if we are using squashfs layers, then those layers are missing on a second run.  Make sure to mount them when we find a built layer.
Closes #454
```release-note
```
> fix: mount previously built squashfs layers if needed

- .github/actions/clean-runner/action.yaml
- .github/actions/show-disk-usage/action.yaml
- .github/workflows/build.yaml
> ci: clean disk before run and show disk usage

- Makefile
- doc/hacking.md
*  Add some documentation to Makefile and doc/hacking.md.
The docker.io bandwidth limit can easily stop a developer from being
able to build or test docker.  Even without the limit, docker.io
is much slower than a local zot or docker repository.
Add documentation on how to set the makefile variable
STACKER_DOCKER_BASE.
Also add information about 'make test' and individual test files.
*  Create a 'test' target separate from 'check'
This just allows you to run 'make test'.  Previously the only
way to run test from make was to call 'make check' which require
running lint also.
> Doc/add some doc about make 

- go.mod
- go.sum
There is a PR against umoci#main to avoid trying to chmod +r when we don't need to.  This will avoid trying to chmod +r on a mountpoint, which is the root cause of #450.
While we can and should also forward port our umoci dep to point at current main, we should not do that as part of this PR, as that will risk confusion if there are regressions from just the fwd port.
Closes #450
```release-note
```
By submitting this pull request, I confirm …
> fix: use a version of umoci with fix for failing chmod

- Makefile
This was a copy/paste error added by my last change to Makefile. Instead of downloading zot to TOOLS_D/bin/zot, we were downloading regclient.  Big surprise, regclient binary doesn't work like zot binary.
Fix the download url, and also update the ZOT_VERSION to include the 'v' for consistency with REGCLIENT_VERSION and GOLANGCI_LINT_VERSION.
> fix: In Makefile, download zot as ZOT rather than regclient

- .github/workflows/build.yaml
- Makefile
- doc/hacking.md
This adds a make target 'docker-clone' which will copy the required docker images to a local oci dir specified by CLONE_D.
You can then use that oci dir as STACKER_DOCKER_BASE.
So:
make docker-clone CLONE_D=/tmp/my-oci
export STACKER_DOCKER_BASE=oci:/tmp/my-oci:
make ...
> chore: Clone images to local oci repo before building

- pkg/types/layer.go
- pkg/types/layer_bind_test.go
- test/binds.bats
Entries stacker.yaml's "binds" are of type Bind.
When imported from yaml, support was present for these three things:
1. ascii art specifying source and dest ("source -> dest")
2. source only ("source")
3. map with 'Source' and 'Dest'.
Support for '3' is dropped, and replaced by map with 'source' and 'dest'.  'Source' and 'Dest' are inconsistent with the rest of stacker.yaml. Note that importing from json still does support capital letter variants as the golang json library is case insensitive.
Improvements to the bind yaml and json support generally rely more heavily on the library to do the lifting.
**If an issue # is not available please add repro steps and logs showing the …
> fix: Improve bind imports, support lower case 'source' in yaml, add go test

- Makefile
- build.yaml
This allows:
make BUILD_D=/tmp/build
Without the change, only a BUILD_D that was under the stacker checkout would work.
Note that in order to take advantage of shared GOCACHE and GOPATH, they must be under BUILD_D (they are by default).
> build: bind BUILD_D in so you can use a BUILD_D outside of the tree.

- cmd/stacker/check.go
stacker tries to avoid symlinks to minimize unexpected behaviors, so add check for that.
```release-note
```
> feat(check): add a check for symlinks in roots-dir path

- pkg/log/log.go
- pkg/overlay/metadata.go
- pkg/stacker/base.go
- pkg/types/layer_type.go
- test/empty-layers.bats
Earlier versions of docker images had empty layers of 1024 zero-valued octets.
```release-note
```
> fix: handle ancient empty docker layers

- doc/stacker_yaml.md
documentation
the description of the `type: oci` field in `from` did not match what the code requires
it fixes the description
https://stackerbuild.io/v0.40.1/reference/stacker_file/#from
yolo
yolo
no
docs only
> docs: make type: oci description match code

- go.mod
- pkg/squashfs/squashfs.go
When using squasfuse, check whether it supports -o notifypipe. If it does, then use that instead of our manual checking the mountpoint inode, which is less reliable.
Co-Developed-by: Serge Hallyn <serge@hallyn.com>
See [previous PR](https://github.com/project-stacker/stacker/pull/519)
Changes compared to the original PR:
* use a version check for figuring out whether the mount notification mechanism is supported
* check whether the pipe signals a successful or an unsuccessful squashfuse mount
This is a new PR because I cannot amend Serge's original PR.
feature
none
It uses the newly available squashfuse notification mechanism.
**If an issue # is not available please add repro steps …
> feat: use squashfuse ready notifier if available

- cmd/stacker/grab.go
- pkg/overlay/overlay-dirs.go
- pkg/stacker/grab.go
- pkg/stacker/import.go
- pkg/types/layer.go
- test/import.bats
> feat(import): copy folder contents

- Makefile
- go.mod
- go.sum
- install-build-deps.sh
- test/gzip.bats
- test/helpers.bash
https://github.com/project-stacker/umoci/commit/89a7ea1a89bd405f527ea60a8c8ceaa38b412084
Use updated umoci (project-stacker's fork) to use a 1 MiB copy buffer. This change brings stacker inline with compression parameters used in containers/image libraries and makes them compatible.
```release-note
```
> fix(umoci)!: umoci's copy buffer set to 1 MiB

- pkg/log/log.go
- pkg/overlay/metadata.go
- pkg/stacker/base.go
- pkg/types/layer_type.go
- test/empty-layers.bats
Earlier versions of docker images had empty layers of 1024 zero-valued octets.
https://github.com/moby/moby/issues/20917#issuecomment-191901912
(cherry picked from commit f0f964216cb7dc1c5ec529ec49824e9a1879ef45)
```release-note
```
> fix: handle ancient empty docker layers (#522)

- pkg/overlay/pack.go
> check whether symlink exists

- .github/workflows/build.yaml
- Makefile
> ci: point docker registry to local copy

- test/cp-not-required.bats
- test/docker-base.bats
- test/import.bats
Some tests were using
type: docker
url: docker://ubuntu:latest
Rather than using:
type: oci
url: oci:${UBUNTU_OCI}
Replacing those with the oci reference drops a test runtime dependency we have on docker hub.
I've left the 'type' of docker in place to test a code path that uses 'type: docker' to refer to 'oci:'.
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> test: drop references to docker:// images from test/

- Makefile
- tools/oci-copy
test: Fix the docker-clone make target to exit failure.
My expectation was that when make invoked the shell (sh) for
a line in a rule was that it did so with '-e'.  That was an
incorrect assumption.
The make docker-clone target was basically doing:
for i in url1 url2 url3; do
something $i; done
The failure of the *last* item in the list should cause the
command to exit failure, but failure of an earlier command would not.
The change here is just to move that shell code into a script in
tools/oci-copy and call it from there.
> test: Fix the docker-clone make target to exit failure.

- .github/workflows/sync-3rdparty-images.yaml
> ci: add a job to sync 3rd party container images

- pkg/overlay/pack.go
BREAKING CHANGE: the default gzip block size is changed to 256<<12, was previously 256<<10.
A tar layer with the same content but compressed with different gzip blocksize will result in different sha256sums in the final OCI Image. Ecosystem tools have one current size in use and stacker's current size differ.
Interactions between a stacker-built OCI image and ecosystem tools which recompress lower layers results in bloated registries which will have identical tar content but different compressed sha256 blobs.
Unfortunately, the OCI image spec doesn't standardize/encode this in the specification document. Hence, we change to the current common block size used in the ecosystem here in the stacker implementation.
We now link against our own fork: github.com/project-stacker/umoci which may …
> fix(gzip)!: change the default block size (#529)

- .github/workflows/ci.yaml
- .github/workflows/coverage.yaml
- Makefile
- build.yaml
- pkg/stacker/build.go
- pkg/test/cover.go
With golang 1.20.x, we can build a binary with coverage support.
> Cover
>
> Go 1.20 supports collecting code coverage profiles for programs
> (applications and integration tests), as opposed to just unit tests.
> 
> To collect coverage data for a program, build it with go build's -cover
> flag, then run the resulting binary with the environment variable
> GOCOVERDIR set to an output directory for coverage profiles. See the
> 'coverage for integration tests' landing page for more on how to get
> started. For details on the design and implementation, see the
> proposal.
**Testing done on this …
> test: add code coverage support

- test/dependency-order.bats
This seems to be a transient failure, but is legitimate issue.
When coverage binary is being used, this test case could fail with:
The /stacker/.coverage file was being updated by the stacker binary itself.  This is just a race condition based on when the file gets written to and when it was being collected by tar.
The change is just to only have tar collect the .cpio files.
```release-note
```
By submitting this pull request, I confirm that …
> test: Fix test failure due to .coverage changing during tar creation.

- .github/workflows/build.yaml
- .github/workflows/coverage.yaml
Uploading a c-i built binary can make it easier for users to test.
```release-note
```
> ci: Upload stacker binary

- .github/workflows/build.yaml
- .github/workflows/coverage.yaml
Uploading artifacts before code coverage appears to impact coverage stats. Perhaps there is a cleanup involved. So do it after.
```release-note
```
> ci: fix upload order

- build.yaml
- cmd/stacker/bom.go
- cmd/stacker/chroot.go
- doc/stacker_yaml.md
- doc/tutorial.md
- pkg/stacker/bom.go
- pkg/stacker/build.go
- pkg/stacker/cache.go
- pkg/stacker/cache_test.go
- pkg/stacker/grab.go
- pkg/types/layer.go
- pkg/types/stackerfile.go
- test/basic.bats
- test/broken-link.bats
- test/build-only.bats
- test/caching.bats
- test/cp-not-required.bats
- test/dependency-order.bats
- test/docker-base.bats
- test/import-http.bats
- test/import.bats
- test/invalid.bats
- test/multi-arch.bats
- test/overlay-dirs.bats
- test/prerequisites.bats
- test/publish.bats
- test/squashfs.bats
- test/unprivileged.bats
This changes the behavior of the 'import' target to behave as it did before the breaking change that moved imports into /stacker/imports/
So now, if the stacker file uses 'import', then imports will be placed in /stacker.  If the stacker file uses 'imports' (plural) then they will be placed in /stacker/imports.
What we actually get in both cases is all the binds being done into either /.stacker (legacy) or /stacker (new).  In the legacy case, the imports are also bind-mounted into /stacker
Legacy (for those that used 'import:')
stacker: /.stacker/bin/stacker
imports: /.stacker/imports -> /stacker
runscript: /.stacker/imports/.stacker-run.sh
artifacts: /.stacker/artifacts
new (for those that use 'imports:')
stacker: /stacker/bin/stacker
imports: /stacker/imports
runscript: …
> feat: Support legacy 'import' directive and use 'imports' for future

- test/bom.bats
This reverts commit da119e7b457dec83e08890f60650f1fbea59453c.
```release-note
```
> revert: "test: add a bom workflow with substitutions (#562)"

- pkg/atomfs/molecule.go
- test/atomfs.bats
Add a cleanup function to unmount underlying atoms if one of the mount fails.
bug
#541
Add a cleanup function which tracks the successfully mounted atoms, and if one
fails, then it will unmount the successful atoms before returning the error.
make check locally.
no
```release-note
```
> fix: Add a verity_cleanup function to test helpers.bash

- test/helpers.bash
2 things are fixed here.
1. Running skopeo as root creates /run/containers with 700 permissions. That causes a problem when you run skopeo as root and then run stacker as non-root.
The error would look like this:
> error: initializing source ... getting username and password: 1 error occurred:
>   * reading JSON file "/run/containers/0/auth.json":
>         open /run/containers/0/auth.json: permission denied
> couldn't import base layer base
> stackerbuild.io/stacker/pkg/stacker.importContainersImage
>       /stacker-tree/pkg/stacker/base.go:141
> stackerbuild.io/stacker/pkg/stacker.GetBase
>       /stacker-tree/pkg/stacker/base.go:49
> stackerbuild.io/stacker/pkg/stacker.(*Builder).build
>       /stacker-tree/pkg/stacker/build.go:407
> …
> fix: Wrap use of skopeo to avoid its unwanted side effects.

- pkg/overlay/pack.go
- test/empty-layers.bats
- test/publish.bats
If a tar layer has a deleted file, a whiteout entry is created. However, when extracting tar and overlay whiteouts are incompatible.
```release-note
```
> fix: use overlay whiteouts when extracting tar layers

- doc/stacker_yaml.md
- pkg/types/stackerfile.go
Putting a date in the deprecation warning message allows users to plan migration more effectively.  The date chosen allows for plenty of time for users to migrate existing stacker.yaml files.
#571.
> fix: Update 'import' deprecation warning with a date.

- Makefile
Skopeo's build target is an inline shell script.
It needs to run with 'set -e' or it will just keep going after it fails.
```release-note
```
> fix: catch failures in makefile when building skopeo

- cmd/stacker/main.go
- test/basic.bats
The following:
stacker build --substitute a=b,c
used to work, until commit 3baba644:
fix(ci): convert ci is failing due to perms (#439)
This squashed PR included 'chore(go.mod): update cli to github.com/urfave/cli/v2'.  Switching from urfave/cli/v1 to v2 changes string slice flag behavior to automatically split on commas.
Luckily there is an app.DisableSliceFlagSeparator flag we can set to tell it not to do that.  Set that flag.  And add a test for this.
**Does this PR introduce any …
> fix: don't break on --substitute values which have commas

- cmd/stacker/publish.go
- pkg/stacker/publisher.go
- test/convert.bats
- test/publish.bats
> refactor: rename 'layer' as 'image' in stacker publish path

- cmd/stacker/bom.go
- go.mod
- go.sum
- pkg/stacker/bom.go
- pkg/types/layer.go
- test/bom.bats
Currently, stacker-bom doesn't include namespace information in the document. Adding a cmdline arg to do so.
```release-note
```
> feat: add namespace arg when producing doc

- go.mod
- go.sum
Update the stacker-bom version to include this support.
```release-note
```
> fix: include license detection support in bom workflows

- go.mod
- go.sum
https://github.com/project-stacker/stacker-bom/pull/57
```release-note
```
> chore: update stacker-bom dep

- go.mod
- go.sum
move umoci version to the commit with the fix for correctly closing tarwriter in all cases, avoiding creation of layers that make gnu tar sad.
bug
```
$ tar tvzf oci/blobs/sha256/bc7f2c15116d3da36aa493221dcf736cbe027f64f3e32b157aafb83da7cba35e
...
-rw-r--r-- 0/0 32064 2024-02-21 19:44 var/log/faillog
-rw-rw-r-- 0/43 292584 2024-02-21 19:44 var/log/lastlog
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
while golang based container tools ignore this EOF, which is fine because it only happens after the last file has been read, many scanners use gnu tar, which errors out and can cause problems.
**If an issue # is not available please add repro steps and …
> umoci: update to get tar writing fix

- .github/workflows/sync-3rdparty-images.yaml
We have been using alpine:edge which is a moving target leading to unpredictable breakages. Let's move to numbered releases.
```release-note
```
> ci: sync a fixed alpine version to use in future

- Makefile
- pkg/stacker/base.go
- pkg/stacker/build.go
- pkg/stacker/publisher.go
- pkg/stacker/referrer.go
- pkg/stacker/referrer_test.go
- test/bom.bats
- test/helpers.bash
When we import an image via the from: directive, also pull in the sbom if there is one. Else we need to rebuild the sbom and there may not be enough state/information to do so.
```release-note
```
> feat: support importing sboms along with images

- pkg/stacker/build.go
- pkg/stacker/cache.go
- pkg/stacker/cache_test.go
- pkg/types/layer.go
- pkg/types/stackerfile.go
- test/caching.bats
Fixes #592 by serializing the `wasLegacyImport` field to ensure that the cache records the correct value when an image has it set.
Includes a test based on Serge's description in #592.
The symptom is an error "cache miss because layer definition was changed" when the definition could not have changed since build. This happens during multi file builds in builds with dependencies, and in build-then-publish flows, where the build will be fine but the publish will fail with the same error.
Using `--debug` to show the cache mismatch shows that somewhere along the line, the layer is being serialized with the wrong default value when writing to the cache.
Needs to change currentCacheVersion to ensure compatibility, see the TestCacheEntryChanged function comment for more info.
> fix: cache: serialize legacy import field

- Makefile
- cmd/stacker/main.go
- pkg/lib/version.go
- pkg/stacker/api.go
- pkg/stacker/build.go
It can be useful to know which version of stacker created an image. Let's put it in there.
Moves some things around to avoid multiple definitions & import loops.
> add stacker version as annotation to images

- test/bom.bats
> ci: fix bom test failure 

- go.mod
- go.sum
- test/basic.bats
> Hallyn 2024 03 18 test rmdir

- go.mod
- go.sum
CI failures indicate that this could be another error code that needs to be handled.
https://github.com/project-stacker/umoci/pull/7
```release-note
```
> fix: handle unix.EACCES error also

- pkg/stacker/bom.go
- pkg/stacker/build.go
- test/bom.bats
From our experience, package information may be removed in such layers making it much harder to discover and auto-construct BOMs.
So allow this for `build_only` layers also.
```release-note
```
> fix: allow bom build and verification for `build_only` layers

- doc/stacker_yaml.md
> fix: fix another incorrect substitution doc

- pkg/stacker/import.go
bug
#617 
when dealing with large files in imports (> 10**10 bytes) then equalfile fails.
this PR uses io.LimitedReader to avoid the error path.
No
No
```release-note
```
> fix: avoid max read size reached error when cmp imported files

- doc/stacker_yaml.md
the yaml value is `runtime_user`, not `user`.
> fix: update stackeryaml ref doc for runtime_user

- pkg/stacker/base.go
- pkg/stacker/import.go
- pkg/stacker/network.go
For import types that will be checked, save the calculated hash of the downloaded file and print them together in the format of a yaml imports section for easy copy and pasting to add hashes to a file.
Because we only the parse file contents after the substitution placeholders are replaced, this isn't a direct copy and paste replacement, but it is an improvement, and it should be easy enough to tell which expanded paths come from what input.
The relevant info is already present if you build with `--debug`, but this consolidates it into one place, and without --debug, the hash is not printed.
Here is an example of the output without --debug:
```
preparing image minbase...
downloading https://host/path/to/atomix-tools-0.5.10.tgz
27.82 MiB / 27.82 MiB …
```
> feat: print hashes for imports in yaml format

- test/bom.bats
With latest stacker-bom (v0.0.7) included, all bom enabled layers must set their annotations.
```release-note
```
> test: fix failing nightly test

- test/bom.bats
In the nightly extended bom tests, we use a centos base layer and hence discovery must be performed.
```release-note
```
> test: fix missing pkgs in bom

- pkg/container/container.go
- pkg/stacker/build.go
Stacker does not check if a bind mount source exists and if the source is a directory then the container crashes with a stack trace that does not indicate that the missing source dir is the issue.
Check if the source exists and return an error indicating the source is missing instead of the container stack trace.
bug
```
$ mkdir test-binds && cd test-binds
$ cat > stacker.yaml <<EOF
hello-binds:
from:
type: docker
url: docker://zothub.io/tools/busybox:stable
binds:
- mydir -> /mydir
run: |
mkdir -p /hello-stacker-app
echo 'echo "Hello Stacker!"' > /hello-stacker-app/hello.sh
EOF
$ stacker build -f …
```
> fix: check bind source file/dir exists

- test/binds.bats
Just copied Ryan's test from the description of #624 with minimal editing.
> chore: add test for failing on missing bind source

- Makefile
- go.mod
- go.sum
- install-build-deps.sh
- pkg/overlay/overlay-dirs.go
- pkg/overlay/pack.go
- pkg/stacker/build.go
- pkg/types/storage.go
- test/publish.bats
- test/whiteout.bats
> fix: remove superfluous userxattr whiteouts

- README.md
Fixes the code coverage URL in README.md
> fix: codecov link on readme

- doc/stacker_yaml.md
we were missing the dict version in the docs
documentation
binds dict style was undocumented
> fix: update docs for bindsdoc

- pkg/lib/dir.go
- pkg/lib/dir_test.go
- pkg/lib/file.go
- pkg/overlay/pack.go
- pkg/stacker/build.go
If the argument to oci-dir exists but is empty, we currently get a confusing error about it not being a layout. Other cases could be better explained while we're at it too.
> build: improve errors for --oci-dir cases

- .github/workflows/build.yaml
- .github/workflows/coverage.yaml
- cmd/stacker/build.go
- cmd/stacker/inspect.go
- cmd/stacker/internal_go.go
- cmd/stacker/publish.go
- cmd/stacker/validate.go
- go.mod
- go.sum
- install-build-deps.sh
- pkg/lib/image_test.go
- pkg/overlay/metadata.go
- pkg/overlay/pack.go
- pkg/types/layer_type.go
- test/atomfs-erofs.bats
- test/atomfs-squashfs.bats
Fixes https://github.com/opencontainers/image-spec/issues/1190
```release-note
```
> feat(erofs): initial commit for erofs support

- .github/workflows/sync-3rdparty-images.yaml
We periodically update our private container image copies. Point to public.ecr.aws/docker/library/ as source.
```release-note
```
> ci: fix sync image sources

- pkg/lib/image.go
- pkg/stacker/base.go
Currently, stacker is bound to the host platform for all its operations. This PR allows for build a container image different from the host platform by overriding the platform OS.
```release-note
```
> feat: add ability to override platform OS
